name: default
default-channel: G
default-listen: [G, Server_Broadcast, Network_Broadcast]
      
# permissions are like, mcnsachat3.ext.admin or such
# permissions to add: ignorelocked, ignoremute
# also, store chat persist (channels and their modes, players and their channels and modes... in a yml file)
# server only stores channels, client only stores players

# permissions so far: mcnsachat3.user.cancolor