name: default
default-channel: G
default-listen: [G, LOCAL_ANNOUNCE, NET_ANNOUNCE]
strings:
  player-welcome: '&aWelcome &e%player% &ato the server!'
  player-join: '%prefix%%player% &ehas joined &7%server%&e!'
  player-quit: '%prefix%%player% &ehas left &7%server%&e!'
  message: '{&7%server%&f} <%channel%&f> [%rank%&f] %player%: &7%message%'
  action: '{&7%server%&f} <%channel%&f> * %prefix%%player% &f%message%'